name: app_riderguard
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
    
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.5.1
  http: ^1.2.1
  go_router: ^16.0.0


  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  google_fonts: ^6.2.1
  logger: ^2.0.2+1
  rive: ^0.13.4
  shared_preferences: ^2.5.3
  flutter_screenutil: ^5.9.3
  lottie: ^3.3.1
  image_picker: ^1.1.2
  path: ^1.9.1
  package_info_plus: ^8.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  build_runner: ^2.4.6
  intl_utils: ^2.8.4

flutter:

  uses-material-design: true

  assets:
    - assets/lang/
    - assets/animations/
    - assets/images/

  # Optional jika tidak pakai google_fonts dan ingin register manual fonts
  # fonts:
  #   - family: Poppins
  #     fonts:
  #       - asset: assets/fonts/Poppins-Regular.ttf
